import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="ja">
      <head />
      <body>
      <header>
        <h1>
          <Link href="/">ブログ</Link>
        </h1>
        <Link href="/articles/new">記事を書く</Link>
      </header>
      {children}
      <footer>
        <small>© 2023 NaoyukiUmeda</small>
      </footer>
      </body>
      </html>
  );
}
