import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import {ChakraProvider} from "@chakra-ui/react";
import Provider from "@/app/Provider";
import Header from "@/app/Header";
import Main from "@/app/Main";
import Footer from "@/app/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="ja">
      <head />
      <body>
      <Provider>
        <Header></Header>
          <Main>{children}</Main>
          <Footer></Footer>
      </Provider>
      </body>
      </html>
  );
}
